---
- hosts: localhost
  connection: local
  remote_user: utx10101
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - gci-utx10101.users
  vars:
    userList:
      - username: gci-2019
        password: "1234"
        shell: /bin/bash
