---
- hosts: localhost
  connection: local
  remote_user: utx10101  
  tasks:
    - name: Capture Status Code of `https://codein.withgoogle.com/`
      capture_http_code:
        url: https://codein.withgoogle.com/
      register: result
    - debug:
        var: result
